name: Build & Release

on:
  push:
    branches: [ main ]

jobs:
  gomod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - run: |
        go version
        go mod tidy

    - uses: chainguard-dev/actions/nodiff@main
      with:
        fixup-command: "go mod tidy"

  gotest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - run: |
        go version
        go test -v ./...

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: bindl-dev/bindl@main
      with:
        install-dir: bin

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: golangci-lint
      run: make gh/lint

  deploy:
    needs:
    - gotest
    - gomod
    - golangci-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: bindl-dev/bindl@main
      with:
        install-dir: bin

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - run: make deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
