name: Build & Release

on:
  push:
    branches: [ main ]

jobs:
  gomod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - run: |
        go version
        go mod tidy

    - uses: chainguard-dev/actions/nodiff@main
      with:
        fixup-command: "go mod tidy"

  gotest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - run: |
        go version
        go test -v ./...

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: bindl-dev/bindl@main
      with:
        install-dir: bin

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: golangci-lint
      run: make gh/lint

  publish:
    runs-on: ubuntu-latest
    needs:
    - gotest
    - gomod
    - golangci-lint
    outputs:
      container-tag: ${{ steps.publish.outputs.container-tag }}
    steps:
    - uses: actions/checkout@v2

    - uses: bindl-dev/bindl@main
      with:
        install-dir: bin

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: Authenticate registry
      run: |
        make koauth PASSWORD=${{ secrets.GITHUB_TOKEN }}

    - id: publish
      name: Push container
      run: |
        make publish-container | xargs -I{} echo ::set-output name=container-tag::{}

  deploy:
    runs-on: ubuntu-latest
    needs:
    - publish
    steps:
    - uses: actions/checkout@v2

    - uses: bindl-dev/bindl@main
      with:
        install-dir: bin

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - run: make deploy IMAGE=${{needs.publish.outputs.container-tag}}
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
